# Generated by Django 5.1.6 on 2025-02-27 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_errorlog_is_corrected"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="name",
            field=models.CharField(default="Default Lesson Name", max_length=255),
        ),
    ]
