# Generated by Django 5.1.6 on 2025-02-27 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_videolesson"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="videolesson",
            name="teacher",
        ),
        migrations.AddField(
            model_name="videolesson",
            name="creator",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="video_lessons",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="videolesson",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="videolesson",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
