# Generated by Django 5.1.6 on 2025-02-28 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_remove_videolesson_teacher_videolesson_creator_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homework",
            name="lesson",
        ),
        migrations.AddField(
            model_name="homework",
            name="student",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="homeworks",
                to="app.student",
            ),
            preserve_default=False,
        ),
    ]
