# Generated by Django 5.2 on 2025-04-07 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_homework_lesson_homework_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
