# Generated by Django 5.2 on 2025-04-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_homework_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='is_corrected',
            field=models.BooleanField(default=False),
        ),
    ]
