# Generated by Django 5.2 on 2025-04-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_homework_is_corrected'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
