# Generated by Django 5.2 on 2025-04-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_homeworkimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
