# Generated by Django 5.2 on 2025-04-10 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_lesson_day_lesson_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_topics', to='app.lesson'),
        ),
    ]
