# Generated by Django 5.2 on 2025-04-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_homework_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='topic',
            field=models.CharField(max_length=255),
        ),
    ]
