# Generated by Django 5.2 on 2025-04-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_homework_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='topic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
