# Generated by Django 5.2 on 2025-04-10 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_homework_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mistake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('is_corrected', models.BooleanField(default=False)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistakelog_set', to='app.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
        ),
        migrations.CreateModel(
            name='MistakeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mistake_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('mistake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.mistake')),
            ],
        ),
        migrations.DeleteModel(
            name='ErrorLog',
        ),
    ]
