# Generated by Django 5.2 on 2025-04-10 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_mistake_mistakeimage_delete_errorlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mistake',
            old_name='is_corrected',
            new_name='is_fixed',
        ),
        migrations.AddField(
            model_name='mistake',
            name='homework',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mistakes_for_homework', to='app.lesson'),
        ),
        migrations.AlterField(
            model_name='mistake',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistakes_for_lesson', to='app.lesson'),
        ),
    ]
