# Generated by Django 5.2 on 2025-04-10 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_is_corrected_mistake_is_fixed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mistake',
            name='lesson',
        ),
    ]
